### 
GET http://localhost:3001
###
### users

GET http://localhost:3001/users
###
### register
POST http://localhost:3001/register
Content-Type: application/json

{    
    "username": "joany",
    "email": "joan@joan.com",
    "password": "123456"
    }
###
### login
POST http://localhost:3001/login
Content-Type: application/json

{    
    "username": "joany",
    "email": "joan@joan.com",
    "password": "123456"
    }

###    
### QUESTIONS

POST http://localhost:3001/questions 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg4NTQ1MjEsImV4cCI6MTY1ODg2MTcyMX0.Cn2yyIdbNgk2C4TYHQFjFV0BTvvkzuMC8ODJq07jx9E

{
"q_title": "Feeding cow", 
"question": "How many times to feed a cow",
"user_id": 2
}


###
###
PATCH http://localhost:3001/questions/2
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg4NTQ1MjEsImV4cCI6MTY1ODg2MTcyMX0.Cn2yyIdbNgk2C4TYHQFjFV0BTvvkzuMC8ODJq07jx9E

{
"question": "How many times a day should I feed puppy nfjgkllkjhjgjg"
}
###
###
GET http://localhost:3001/questions 

### ANSWERS
###
POST http://localhost:3001/answers 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTY1MzY0NDU1MiwiZXhwIjoxNjUzNjUxNzUyfQ.saWN9Y5YSh9wVJ2cZwwL8UU9Z0jkRdpkrqLiNkIaGaM

{
"group_id": "3", 
"user_id": "7"
}
###
###
GET http://localhost:3001/answers 


