### 
GET http://localhost:3001
###
### users

GET http://localhost:3001/users
###
### register
POST http://localhost:3001/register
Content-Type: application/json

{    
    "username": "sammmyy",
    "email": "sam@sam.com",
    "password": "123456"
    }
###
### login
POST http://localhost:3001/login
Content-Type: application/json

{    
    "username": "joany",
    "email": "joan@joan.com",
    "password": "123456"
    }

###    
### QUESTIONS

POST http://localhost:3001/questions 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg4NTQ1MjEsImV4cCI6MTY1ODg2MTcyMX0.Cn2yyIdbNgk2C4TYHQFjFV0BTvvkzuMC8ODJq07jx9E

{
"q_title": "Feeding cow", 
"question": "How many times to feed a cow",
"user_id": 2
}

###
PATCH http://localhost:3001/questions/1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyMDMwNDksImV4cCI6MTY1OTIxMDI0OX0.13L7f8tyHQDjlu5R8gFjNK6PCayHPCEuwaO0b48M8Bw

{
"question": "Puppy bathing ed"
}


###
DELETE http://localhost:3001/questions/5
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg4NTQ1MjEsImV4cCI6MTY1ODg2MTcyMX0.Cn2yyIdbNgk2C4TYHQFjFV0BTvvkzuMC8ODJq07jx9E


###
GET http://localhost:3001/questions 
###
GET http://localhost:3001/questions/1
###
GET http://localhost:3001/questions/user/2

### ANSWERS
###
POST http://localhost:3001/questions/1/answers 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MTU2NTMsImV4cCI6MTY1ODkyMjg1M30.wVkUp1fzmxwKrK3yad-I2Hf991-ISy2aNSh7HXDhOsY


{
"user_id": "2",
"answer": "from 4 weeks"
}
###
###
GET http://localhost:3001/questions/1/answers


###
GET http://localhost:3001/answers/user/2


###
PATCH http://localhost:3001/answers/5
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MTU2NTMsImV4cCI6MTY1ODkyMjg1M30.wVkUp1fzmxwKrK3yad-I2Hf991-ISy2aNSh7HXDhOsY

{

"answer": "or maybe 5w edited"
}


###
DELETE http://localhost:3001/answers/5
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MTU2NTMsImV4cCI6MTY1ODkyMjg1M30.wVkUp1fzmxwKrK3yad-I2Hf991-ISy2aNSh7HXDhOsY
